encoding: utf-8

# 其他页面site.title等都是引用这里

# SEO相关信息
title: 林秀栋的技术博客
description: 个人技术博客
keywords: Html,Css,Js,前端
author: lxd

# 项目环境
# 静态资源找不到，链接点进去不对时请检查下这里的配置
# demo.com访问设置为""，demo.com/blog/访问设置为"/blog"
context: "/myBlog"

# 用来生成sitemap
# siteMapPrefix: "http://blog.tmaize.net"

## 文章url前缀，固定格式，不要动
permalink: /posts/:year/:month/:day/:title.html

# 页面底部信息
# copyright: 2017
# record: "栋栋栋栋锵"

coderay:
  coderay_tab_width: 01
